apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo
spec:
  selector:
    matchLabels: 
        app: spring-boot-demo
        
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring-boot-demo
        tier: display
    spec:
      containers:
        - image: sujil02/spring-boot-demo
          name: spring-boot-demo
          #image: gcr.io/Pipelines/nginx:1.7.9
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080