apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-demo
  labels:
   app: spring-boot-demo
spec:
  containers:
  - name: spring-boot-demo
    image: sujil02/spring-boot-demo
    ports:
      - containerPort: 8090