apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo
  labels:
    app: spring-boot-demo
spec:
  type: NodePort
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8080
      nodePort: 30091
  selector:
    app: spring-boot-demo
    tier: display